Improved the Creator Styling Section
CMoore97/JBEC pull request #31
Opened 2017-11-28 04:49 UTC by Nilrre

2017-11-28 06:30 UTC, BorisHo1 approved these changes

2017-11-28 06:53 UTC, Tyeboe commented
Allow centering of text.

Fix the issue where font-size isn't changing.

Issue with how you are applying your styles and the way I had mine set up but we'll fix it later (Do not consider in regard to merging request).

Improve the styling of the controls themselves. (Get rid of black and grey background and make them look more like the rest of the site.)

2017-11-28 06:54 UTC, Tyeboe requested changes
Allow centering of text.

Allow bold and italicized text.

Fix the issue where font-size isn't changing.

Issue with how you are applying your styles and the way I had mine set up but we'll fix it later (Do not consider in regard to merging request).

Improve the styling of the controls themselves. (Get rid of black and grey background and make them look more like the rest of the site.)

2017-11-28 22:00 UTC, BorisHo1 approved these changes

2017-11-29 21:37 UTC, BorisHo1 approved these changes

2017-12-02 18:07 UTC, Tyeboe approved these changes

2017-12-04 18:16 UTC, merged