Created/Styled Home Page
CMoore97/JBEC pull request #34
Opened 2017-11-28 09:10 UTC by BorisHo1

2017-11-28 18:31 UTC, Tyeboe requested changes
You need to go into all of your projects properties pages and use Framework Version 4.7.
Other than that looks good

2017-11-28 22:00 UTC, CMoore455 approved these changes

2017-11-29 22:23 UTC, Tyeboe approved these changes

2017-11-29 22:45 UTC, Nilrre approved these changes

2017-11-29 22:46 UTC, merged