Upload header templates
CMoore97/JBEC pull request #40
Opened 2017-12-01 20:56 UTC by Nilrre

2017-12-01 21:48 UTC, BorisHo1 approved these changes

2017-12-01 22:33 UTC, CMoore455 approved these changes

2017-12-02 18:04 UTC, Tyeboe commented
Don't make it an entire page. You're just pushing up samples for a header that would be contained inside the body tag of another document.

2017-12-02 18:06 UTC, Tyeboe requested changes
^
  |

2017-12-05 17:02 UTC, Tyeboe requested changes

2017-12-05 17:02 UTC, Tyeboe commented on c.html
> +    <div>Link</label>
Opening divs and closing labels

2017-12-05 17:02 UTC, Tyeboe commented on d.html
> +    <div>Link2</label>
Opening divs and closing labels

2017-12-05 17:02 UTC, Tyeboe commented on e.html
> +    <div>Link2</label>
Opening divs and closing labels

2017-12-06 08:42 UTC, Tyeboe approved these changes

2017-12-06 08:42 UTC, merged